In [126]:
from sklearn import datasets
import numpy as np

In [167]:
mydata=datasets.load_digits()


In [128]:
#data seoarartion
X_input=mydata.data
Y_target=mydata.target


In [129]:
print(type(X_input))

<class 'numpy.ndarray'>


In [130]:
type(Y_target)

numpy.ndarray

In [131]:
#split the data into training and testing
from sklearn.model_selection import train_test_split

In [132]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X_input,Y_target,test_size=.30,random_state=101)

In [133]:
Xtrain.shape

(1257, 64)

In [134]:
Xtest.shape

(540, 64)

In [135]:
Ytest.shape

(540,)

In [136]:
Ytrain.shape

(1257,)

In [137]:
from sklearn.svm import SVC

In [138]:
trainer=SVC(gamma=.001) 
#gamma=learning_rate

In [139]:
learner=trainer.fit(X_input,Y_target)

In [140]:
Ya=Ytest
Yp=learner.predict(Xtest)

In [141]:
from sklearn.metrics import accuracy_score

In [142]:
acc=accuracy_score(Ya,Yp)*100
acc

100.0

In [143]:
#read image for testing from computer
from scipy import misc

In [144]:
mytestimage=misc.imread(r"7.jpg")

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """Entry point for launching an IPython kernel.


In [145]:
mytestimage.shape

(256, 256, 3)

In [146]:
mytestimage.dtype

dtype('uint8')

In [147]:
image8_8=misc.imresize(mytestimage,(8,8))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  """Entry point for launching an IPython kernel.


In [148]:
image8_8.shape

(8, 8, 3)

In [149]:
image8_8

array([[[ 0,  0,  0],
        [24, 24, 24],
        [38, 38, 38],
        [29, 29, 29],
        [20, 20, 20],
        [16, 16, 16],
        [ 2,  2,  2],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [29, 29, 29],
        [48, 48, 48],
        [57, 57, 57],
        [69, 69, 69],
        [99, 99, 99],
        [12, 12, 12],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  1],
        [57, 57, 57],
        [46, 46, 46],
        [ 1,  1,  1],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [27, 27, 27],
        [66, 66, 66],
        [ 2,  2,  2],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 6,  6,  6],
        [73, 73, 73],
        [16, 16, 16],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [48, 48, 48],
        [47, 47, 47],
        [ 0,  0,  0],


In [150]:
image_float=image8_8.astype(mydata.images.dtype)

In [151]:
type(image_float.dtype)

numpy.dtype

In [152]:
#scaling maxvalue=15 and meanvalue=0

In [153]:
image0_15=misc.bytescale(image_float,high=16,low=0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `bytescale` is deprecated!
`bytescale` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
  """Entry point for launching an IPython kernel.


In [154]:
image0_15

array([[[ 0,  0,  0],
        [ 4,  4,  4],
        [ 6,  6,  6],
        [ 5,  5,  5],
        [ 3,  3,  3],
        [ 3,  3,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 5,  5,  5],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [11, 11, 11],
        [16, 16, 16],
        [ 2,  2,  2],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 9,  9,  9],
        [ 7,  7,  7],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 4,  4,  4],
        [11, 11, 11],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  1],
        [12, 12, 12],
        [ 3,  3,  3],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 8,  8,  8],
        [ 8,  8,  8],
        [ 0,  0,  0],


In [155]:
image_new_float=image0_15.astype(mydata.images.dtype)

In [156]:
image_new_float

array([[[ 0.,  0.,  0.],
        [ 4.,  4.,  4.],
        [ 6.,  6.,  6.],
        [ 5.,  5.,  5.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 5.,  5.,  5.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [11., 11., 11.],
        [16., 16., 16.],
        [ 2.,  2.,  2.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 9.,  9.,  9.],
        [ 7.,  7.,  7.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 4.,  4.,  4.],
        [11., 11., 11.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 1.,  1.,  1.],
        [12., 12., 12.],
        [ 3.,  3.,  3.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.

In [157]:
mylist=[]
for i in image_new_float:
    for j in i:
     mylist.append(sum(j)/3.0)

In [158]:
print( mylist)

[0.0, 4.0, 6.0, 5.0, 3.0, 3.0, 0.0, 0.0, 0.0, 5.0, 8.0, 9.0, 11.0, 16.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.0, 7.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 11.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 12.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 10.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [159]:
test_image_array=np.array(mylist)

In [160]:
test_data=test_image_array.reshape(1,64)

In [161]:
type(test_image_array)

numpy.ndarray

In [162]:
test_data.shape

(1, 64)

In [163]:
learner.predict(test_data)

array([7])